qlik-oss/sn-action-button

src/ext.js, src/index.js
Simply connected the ext def so that sense can see the property def. Currently the style properties doesn't work properly, but they are to be removed anyway.
=> feat: connect ext def to nebula def

.eslintrc.json, src/components/action-button.js, src/ext.js, src/index.js, src/utils/theme-resolver.js
First styling and property panel settings
=> feat: adding styling and first property panel

README.md
Seems like coveralls needs a new build for it to show the stats.
=> Update README.md with coveralls

.github/semantic.yml, package.json, yarn.lock
Bumps nebula to a version that supports async/await
=> chore(deps): update nebula.js/cli to v0.1.0-alpha.21

src/ext.js, src/utils/__tests__/actions.spec.js, src/utils/actions.js
Only changes the value for the session, so not setting properties.
=> feat: Set variable action

src/__tests__/ext.spec.js, src/ext.js, src/utils/actions.js
Adding a checkbox to show/hide system variables in the list
Also removed `enigmaModel` since we don't want to expose that.
=> feat: Dropdown for variables + expression for values

src/components/action-button.js, src/ext.js, src/utils/__tests__/actions.spec.js, src/utils/actions.js
Maybe should update the unit test and mock `qStateName`, check if `getField()` is called with it. Not sure if we want sense specific things in there if we don't have to (tests run fine now without the mock).
=> feat: Alternate states

package.json
This includes translation string for the button in order to remove the commented string in client
=> chore: bump version to 0.2.1

src/ext.js, src/utils/__tests__/conversion.spec.js, src/utils/conversion.js
Thanks to Christian who pointed out that we can handle this in the action button as well :)
TODO:
- Convert expression for field selection
=> feat: adding conversion to action button

package.json
Preparing a new release for testing
=> chore: 0.3.0

src/__tests__/ext.spec.js, src/ext.js
Also changing the labels for the dropdown labels to singular, requested by UX.
=> feat: label field for actions

src/__tests__/ext.spec.js, src/ext.js
=> fix: make sure actions get titles when converting

src/utils/__tests__/color-utils.spec.js, src/utils/color-utils.js, src/utils/style-formatter.js
waiting for confirmation from visual
=> fix: default border color

src/utils/__tests__/conversion.spec.js, src/utils/conversion.js
fixed so that titles and showTitles setting is the same when converting from old button
=> fix: convert titles

src/components/__tests__/action-button.spec.js, src/components/action-button.js
the disabled property was basically just causing the bug, and not actually disabling the button
=> fix: removed disabled property from disabled button

src/utils/__tests__/actions.spec.js, src/utils/actions.js
https://jira.qlikdev.com/browse/QB-842
=> fix: convert date

src/__tests__/ext.spec.js, src/ext.js, src/utils/__tests__/actions.spec.js, src/utils/__tests__/conversion.spec.js, src/utils/actions.js, src/utils/conversion.js
Adding this action would solve a bug and make sure we have full feature parity.
I also want to revert the fix I made for dates, since it only covers some cases. Not sure if that is possible since it was delievered in MS36. Will look into how this should be released.
=> feat: add selectMatchingValues action

package.json
SInce this includes a new action, i consider this a "minor" bump, not a patch
=> chore: v1.4.0

package.json
=> chore: version 1.4.1

package.json
So release/1.3.0-patch already contains the cherry-picked commit, and will be the release branch for feb 2020
=> chore: v1.3.0-patch-1

src/ext.js
See: https://github.com/qlik-trial/sense-client/pull/13578
=> feat: enable quick mobile

src/__tests__/default-button-props.js, src/__tests__/ext.spec.js, src/__tests__/index.spec.js, src/components/action-button.js, src/ext.js, src/index.js, src/utils/__tests__/navigation-actions.spec.js, src/utils/navigation-actions.js, src/utils/util.js
Part of PS-14085 - sheet show condition
https://jira.qlikdev.com/browse/SUI-6806
The action button will take into consideration the show condition and go to the visible last or first sheet.
Feature flag: **SHEET_SHOW_CONDITION**
Changes are deployed here: https://rd-dyw-0536.rdlund.qliktech.com/
=> feat: navigation in action button and sheet with show condition

package.json
=> chore: version 1.8.0

src/__tests__/index.spec.js, src/components/action-button.js, src/ext.js, src/index.js, src/utils/__tests__/actions.spec.js, src/utils/__tests__/navigation-actions.spec.js, src/utils/actions.js, src/utils/navigation-actions.js
Adds doReload as an Action, with the partial flag possible.
My prettier settings did some things, but the lint passed so..
=> feat: add doReload action

src/__tests__/index.spec.js, src/components/action-button.js, src/ext.js, src/index.js, src/utils/__tests__/navigation-actions.spec.js, src/utils/navigation-actions.js
=> chore: remove flags

src/utils/__tests__/style-formatter.spec.js, src/utils/style-formatter.js
The button was getting offset on high display zoom
now it doesn't
=> fix: button position when zooming

src/index.js
Allows the button to respond to client focus actions, and directly triggering a click!
Requires client update
=> feat: add imperative handle for client focus

src/utils/__tests__/actions.spec.js, src/utils/actions.js
Added a doSave to bookmark creation when executing automation with current selections so when app is opened by automation bookmark is available to be applied.
=> fix: add saveObjects call to bookmark creation on automation execute action

.circleci/config.yml, .eslintrc.json, aw.config.js, jest.config.js, package.json, src/__tests__/default-button-props.js, src/__tests__/ext.spec.js, src/__tests__/index.spec.js, src/components/__tests__/action-button.spec.js, src/components/action-button.js, src/index.js, src/utils/__tests__/actions.spec.js, src/utils/__tests__/color-utils.spec.js, src/utils/__tests__/conversion.spec.js, src/utils/__tests__/navigation-actions.spec.js, src/utils/__tests__/property-resolver.spec.js, src/utils/__tests__/style-formatter.spec.js, src/utils/__tests__/url-utils.spec.js, yarn.lock
Switch to jest as unit test runner. 
TODO:
=> chore: jest as unit test runner

.circleci/config.yml, .github/CONTRIBUTION.md, README.md
Based on sn-tables ci script. Publishes if on master, the tag and version in package.json has been bumped
=> ci: update script to publish from ci

.circleci/config.yml
Hello! As part of our api compliance migration, I have created this PR to ensure this repo is using the new service. Please check that the ci build works correctly and that the information looks correct.
=> chore: migrate api compliance

src/utils/__tests__/actions.spec.js, src/utils/actions.js
Needed to update hasInputs to inputs to support change in automation api.
=> fix: changed hasInputs to inputs

.circleci/config.yml
attempting to fix version not being passed to the VER variable correctly on circle ci.
=> chore: version not being passed to variable

src/object-properties.js
Updated API spec changes for refresh dynamic views and odag launch changes.
=> docs: added api specs for refresh dynamic views and odag launch

src/utils/__tests__/style-formatter.spec.js, src/utils/style-formatter.js
```
.Absolute-Center {
margin: auto;
position: absolute;
top: 0; left: 0; bottom: 0; right: 0;
}
```
Reference:
https://www.smashingmagazine.com/2013/08/absolute-horizontal-vertical-centering-css/
=> fix: center button within its parent element

.eslintrc.json, package.json, src/ext.js, src/utils/__tests__/actions.spec.js, src/utils/actions.js, src/utils/color-utils.js, yarn.lock
no matter which device or IDE, the format will be the same
=> chore: make format code be consistent

src/utils/__tests__/actions.spec.js, src/utils/__tests__/navigation-actions.spec.js, src/utils/actions.js, src/utils/navigation-actions.js
Off-board FF REFRESH_DYNAMIC_VIEWS_ODAG_POPUP
=> chore: off-board FF REFRESH_DYNAMIC_VIEWS_ODAG_POPUP

src/utils/__tests__/actions.spec.js, src/utils/actions.js
Small bug fix to handle new automations API
=> fix: automation API update fix

README.md, package.json
Updates the Nebula dependency and enables the systemJS build artifact.
=> chore: enable systemjs build

src/object-properties.js, src/utils/__tests__/style-formatter.spec.js, src/utils/style-formatter.js, src/utils/style-utils.js, test/rendering/__fixtures__/scenario_1.fix.js
**Issue:**
sizeBehavior doesn't have a compatibility with the old button
**Fix:**
Refactor the conditions to set any conditions other than `fixed` and `fluid` to `responsive ` which is the default value.
More rendering-tests added via this PR: #375
=> fix(QB-18860): button fontSizeBehavior is not compatible
