src/utils/__tests__/conversion.spec.js, src/utils/conversion.js
Assuming we need to remove it?
=> fix: convert switchToEdit to none

src/__tests__/default-button-props.js, src/utils/__tests__/style-formatter.spec.js, src/utils/style-formatter.js
So making sure we get a correct label from the `expression-with-dropdown` component, both the label and value can be used in an expression now.
Also found that the `layout` was not resetting, so hade do parse it.
=> fix: sanity check for correct label + test updates

src/__tests__/ext.spec.js, src/ext.js
Part of PS-14085 - sheet show condition
This PR is part of visual changes for hidden sheets on the action button https://jira.qlikdev.com/browse/SUI-6772
Feature flag: SHEET_SHOW_CONDITION
Add show condition to be part of the options of the extension, this will help to evaluate the show condition on the sheet and display the visual icon if the sheet is hidden.
Changes on the client side are covered in this PR:
https://github.com/qlik-trial/sense-client/pull/14422
=> feat: add option show condition

api-specifications/properties.json, src/object-properties.js
As I was creating examples I noticed that you can't do icons outside sense
=> docs: add exception for icons

tools/validate-nebula-package.js
Removing the stuff related to adding info for the qext in the package file. since it automatically picks up the name and other info anyway, no need to specify and check for it.
=> chore: fix prepack

.circleci/config.yml
config had the id corresponding to sn-table api. Created monitoring for sn-action-button and added the corresponding api id here.
=> chore: update api id for ci config

src/object-properties.js
Sets the default values of:
- showDetails: false - hides the show detaisl option as it isn't relevant
- disableNavMenu: true - disables the navigation menu
=> feat: set default props

api-specifications/properties.json, src/ext.js, src/object-properties.js, src/style-defaults.js, src/styling-panel-definition.js, src/utils/__tests__/style-formatter.spec.js, src/utils/style-formatter.js, src/utils/style-utils.js
**In this PR:** 
Enable styling panel chart tab which includes the listed items: (the backward compatibility has also been considered)
- Enabling Chart tab
- FontFamily dropdown
- Font style
- Text align
- FontSize
- FontColor (single and expression)
- Reset the Label section option
**Feature-flag:** SENSECLIENT_IM_1525_STYLINGPANEL_BUTTON
**Note:** To be able to test it locally, sense-client needs to be linked to analytic changes on my branch [here](https://github.com/qlik-trial/analytics/pull/401) and for getting new translations to [sense-client](https://github.com/qlik-trial/sense-client/pull/23139)
**Unsolved Issues:**
- The font size tooltip looks like moving behind the font styling wrapper in its current location. If we consider LayoutBehavior component which is supposed to be set …
=> feat: enable Chart styling panel for label styling

src/ext.js, src/object-properties.js, src/style-defaults.js, src/styling-panel-definition.js, src/utils/__tests__/style-formatter.spec.js, src/utils/color-utils.js, src/utils/style-formatter.js, src/utils/style-utils.js
The background and border styling options have been added to the action-button chart styling panel, it includes the listed items.  
- Background color
- Background Image using MediaLibrary
- Border
- Reset the section
Feature-flag: SENSECLIENT_IM_1525_STYLINGPANEL_BUTTON
Note: To be able to test it locally, sense-client needs to be linked to analytic changes on my branch https://github.com/qlik-trial/analytics/pull/401 and for getting new translations to https://github.com/qlik-trial/sense-client/pull/23139
Unsolved Issues of the current PR:
- Color Picker preview boxes are not showing the default colors that should be fixed in the coming PRs.
- The position grid does not show focus on center at the beginning. It is because the old and new version of positionGrid component take different …
=> feat: add background options and borders to styling panel

src/object-properties.js, src/utils/automation-props.js
This will probably break the API check. We should not have exposed this in the first place. Might have to do a major button release because of this
=> fix: remove automationshowtriggered

src/styling-panel-definition.js, src/utils/__tests__/style-formatter.spec.js
This PR fixed the issue of 
- Changing the mode from 'media' to 'none', the background image URL will be deleted. However, the URL should only be deleted if the panel section is reset.
=> fix: changing mode from media to none deletes the url value

src/object-properties.js, src/style-defaults.js, src/styling-panel-definition.js, src/utils/__tests__/style-formatter.spec.js, src/utils/__tests__/style-utils.spec.js, src/utils/style-formatter.js, src/utils/style-utils.js, test/rendering/__fixtures__/scenario_1.fix.js
This PR is mostly based on @niekvanstaveren and @a-m-dev developments of font size behavior. [#312](https://github.com/qlik-oss/sn-action-button/pull/312), [#331](https://github.com/qlik-oss/sn-action-button/pull/331)
The font size behavior drop down is added which provides three options of `responsive`, `fluid `and `fixed `font scaling.
**Options definitions:**
- **Fixed** in which the font size is independent of the box size and the length of the text
- **Fluid** in which the font size adapts to the size of the box
- **Responsive** in which the font size adapts to the size of the box and the length of text.
=> feat: add font size behavior dropdown

src/utils/__tests__/actions.spec.js, src/utils/__tests__/automation-helper.spec.js, src/utils/automation-helper.js, src/utils/automation-props.js
**Automation action:**
- Fixed a bug with the copy block button which was causing the bookmark id to not be populated correctly when pasting it into an automation
- Instead of sending the identity provider subject in the user field of the payload to the automation, we are now sending the user id. This is based on feedback from presales
- 2 helper texts were previously only displaying in the properties after setting the property to true - these are now set to always display based on feedback from the automation team
=> fix: copy block, user id and prop hiding updates

src/__tests__/styling-panel-definition.spec.js, src/object-properties.js, src/style-defaults.js, src/styling-panel-definition.js, src/utils/__tests__/style-formatter.spec.js, src/utils/style-utils.js
Adding the input box to insert an exact font size in px when the action button size behavior is set on `fixed` mode. 
The code is almost the same code @niekvanstaveren has been committed here: #312 
https://user-images.githubusercontent.com/20701546/231479760-21bda4ac-5419-417c-835a-1b6a75ea833c.mp4
=> feat: add font size input box to labelSection

src/__tests__/index.spec.js, src/utils/__tests__/automation-helper.spec.js, src/utils/automation-helper.js, src/utils/html-encoder.js
**Issue:** 
- Snackbar currently shows a user defined string when the user runs an automation which updates the run title or uses the output block
**Solution:** 
- The user defined string is now encoded before showing it in the snackbar
=> fix: preventing XSS (QB-19372)

api-specifications/properties.json, src/object-properties.js, src/style-defaults.js, src/styling-panel-definition.js, src/utils/__tests__/style-formatter.spec.js
It has been decided to turn back the sizeBehavior default value of sn-action-button to `responsive`.
=> chore: set responsive as sizeBehavior default value

src/utils/__tests__/actions.spec.js, src/utils/actions.js
Before when activating a bookmark through action button, a layout wouldnt be applied if there was one before. Now we check if the bookmark we want to use has a layout and if it does we remove all previous layout so the new one can be applied.
Tested on localhost.
=> fix: make sure bookmark layout gets applied to app

api-specifications/properties.json, src/ext.js, src/object-properties.js, src/utils/__tests__/style-formatter.spec.js, src/utils/style-formatter.js
Adding a toggle so that the button label can be hidden while still set to a text - this text is then available to screen readers
=> feat: add showLabel toggle so that label can be hidden (a11y)

src/utils/__tests__/actions.spec.js, src/utils/actions.js
Remove actions which do no work with `softLock` (the checkbox label suggests that they should overwrite locked fields, but this does not work, which is also in accordance with Engine design).
I have gone through all actions and found that it works only for the following actions. For others I have removed the checkbox:
- clearAll
- selectAll
- selectAlternative
- selectExcluded
- selectValues
The same has been done in sense-client for sheet actions and this PR will make them aligned.
=> fix: remove unsupported softLock actions

src/ext.js
Use newly created fullscreen support prop to disable fullscreen support for this chart.
fullscreen support prop added here: https://github.com/qlik-trial/sense-client/pull/25161
Used by new line object (`sn-shape`) like so https://github.com/qlik-trial/sn-shape/pull/148
The prop removes the fullscreen option from the nav menu and the context menu.
Will create PR in sense-client to remove hardcoded checks for action-button and instead rely on the fullscreen support prop
Also changing booleans to actual booleans for readability.
=> fix: use fullscreen flag to disable fullscreen support

src/hooks/use-load-image.js
It fixes the console type error of:
=> fix: undefined background property

src/components/__tests__/action-button.spec.js, src/components/action-button.js
When having a button as master item useProperties would return the properties from the master item instead of the button properties
=> fix: use effective properties runtime evaluation
